apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: istio-service-authorization-policy
 namespace: knative-serving
spec:   
 rules:
 - from:
   - source:
       principals: ["*"]
   to:
   - operation:
       methods: ["*"]   