apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cache-deployer-clusterrole.yaml
  - cache-deployer-clusterrolebinding.yaml
  # HACK: although a service account(SA) is not a cluster-scoped resource.
  # Presence of a SA referred by a clusterrolebinding allows kustomize to auto-add
  # namespace for the clusterrolebinding's SA ref.
  - cache-deployer-sa.yaml
  
images:
- name: gcr.io/ml-pipeline/cache-deployer
# with patch https://github.com/kubeflow/pipelines/commit/58584e1d1f64c1e1658cec92f82dd28206797fb2
  newName: milung/cache-deployer
  newTag: v1.0.0-patch